site_name: TOD attack miner
theme: readthedocs

nav:
- Introduction: 'index.md'

markdown_extensions:
- admonition
- plantuml_markdown:
    server: http://www.plantuml.com/plantuml  # PlantUML server, for remote rendering
